apiVersion: portal.gloo.solo.io/v1beta1
kind: APIDoc
metadata:
 name: httpbin-schema
 namespace: httpbin
spec:
 ## specify the type of schema provided in this APIDoc.
 ## openApi is only option at this time.
 openApi:
   content:
     # we use a fetchUrl here to tell the Gloo Portal
     # to fetch the schema contents directly from the petstore service.
     # 
     # configmaps and inline strings are also supported.
    fetchUrl: https://raw.githubusercontent.com/solo-io/solo-blog/main/zero-to-gateway/httpbin-openapi.json